apiVersion: v1
kind: Secret
metadata:
  name: theatre-secret
type: Opaque
stringData:
  POSTGRES_DB: theatre_db
  POSTGRES_USER: theatre_user
  POSTGRES_PASSWORD: theatre123
  SPRING_DATASOURCE_USERNAME: theatre_user
  SPRING_DATASOURCE_PASSWORD: theatre123